# Generated by Django 5.1.2 on 2024-10-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('idea_image', models.ImageField(blank=True, null=True, upload_to='idea_images/', verbose_name='Idea Image')),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
