# Generated by Django 5.1.2 on 2024-11-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0022_mockuplibrary_description'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mockup_libraries',
            field=models.ManyToManyField(blank=True, related_name='products', to='mockups.mockuplibrary'),
        ),
        migrations.AddField(
            model_name='product',
            name='mockups',
            field=models.ManyToManyField(blank=True, related_name='products', to='mockups.mockup'),
        ),
    ]
