# Generated by Django 5.1.2 on 2024-11-04 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0009_remove_design_status'),
        ('products', '0002_product_mockup_libraries_product_mockups'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='designs',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='designs.design'),
            preserve_default=False,
        ),
    ]
