# Generated by Django 5.1.2 on 2024-11-04 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0023_rename_productcategory_mockupcategory_and_more'),
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='mockup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='mockups.mockup'),
        ),
    ]
