# Generated by Django 5.1.2 on 2024-11-07 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0023_rename_productcategory_mockupcategory_and_more'),
        ('products', '0009_libraryproductimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libraryproductimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='library_product_images', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='mockup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mockup', to='mockups.mockup'),
        ),
    ]
