# Generated by Django 5.1.2 on 2024-11-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_libraryproductimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='department',
            field=models.CharField(default='Undefined', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='division',
            field=models.CharField(default='Undefined', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='item',
            field=models.CharField(default='Undefined', max_length=75),
            preserve_default=False,
        ),
    ]
