# Generated by Django 5.1.2 on 2024-10-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mockup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_created=True, auto_now_add=True, null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('mockup_image', models.ImageField(blank=True, null=True, upload_to='mockups/production_images/', verbose_name='Mockup Image')),
                ('mockup_box_image', models.ImageField(blank=True, null=True, upload_to='mockups/box_images/', verbose_name='Mockup Box Image')),
                ('gender', models.CharField(choices=[('Neutral', 'Neutral'), ('Male', 'Male'), ('Female', 'Female'), ('Coed', 'Coed')], default='Neutral', max_length=10)),
                ('product_category', models.CharField(choices=[('General', 'General'), ('Tshirt', 'Tshirt')], default='General', max_length=75)),
                ('bbox', models.CharField(default=None, max_length=50, null=True, verbose_name='Bbox')),
                ('height', models.IntegerField(default=None, null=True, verbose_name='Height')),
                ('width', models.IntegerField(default=None, null=True, verbose_name='Width')),
                ('rotation', models.FloatField(default=None, null=True, verbose_name='Rotation')),
            ],
        ),
    ]
