# Generated by Django 5.1.2 on 2024-10-25 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockup',
            name='product_category',
        ),
    ]
