# Generated by Django 5.1.2 on 2024-10-25 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0002_remove_mockup_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Product Category')),
            ],
        ),
        migrations.AddField(
            model_name='mockup',
            name='product_category',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='mockups.productcategory'),
        ),
    ]
