# Generated by Django 5.1.2 on 2024-10-25 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0003_productcategory_mockup_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='product_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mockups', to='mockups.productcategory'),
        ),
    ]
