# Generated by Django 5.1.2 on 2024-10-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0006_alter_mockup_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, to='mockups.tag'),
        ),
    ]
