# Generated by Django 5.1.2 on 2024-10-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0008_alter_mockup_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Library Name')),
                ('description', models.TextField(blank=True, null=True)),
                ('mockups', models.ManyToManyField(blank=True, related_name='libraries', to='mockups.mockup')),
            ],
        ),
    ]
