# Generated by Django 5.1.2 on 2024-10-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0009_mockuplibrary'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MockupLibrary',
        ),
    ]
