# Generated by Django 5.1.2 on 2024-10-26 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0010_delete_mockuplibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MockupLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mockups', models.ManyToManyField(blank=True, to='mockups.mockup')),
            ],
        ),
    ]
