# Generated by Django 5.1.2 on 2024-10-26 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0011_mockuplibrary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockuplibrary',
            name='mockups',
        ),
    ]
