# Generated by Django 5.1.2 on 2024-10-26 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0013_rename_name_mockuplibrary_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuplibrary',
            name='mockups',
            field=models.ManyToManyField(blank=True, to='mockups.mockup'),
        ),
    ]
