# Generated by Django 5.1.2 on 2024-10-26 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0014_mockuplibrary_mockups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='color')),
                ('hex_code', models.CharField(max_length=10, verbose_name='hex_code')),
            ],
        ),
    ]
