# Generated by Django 5.1.2 on 2024-10-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0015_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hex_code',
            field=models.CharField(max_length=20, verbose_name='hex_code'),
        ),
    ]
