# Generated by Django 5.1.2 on 2024-10-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0016_alter_color_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='category',
            field=models.CharField(max_length=50, null=True, verbose_name='color_category'),
        ),
    ]
