# Generated by Django 5.1.2 on 2024-10-27 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0017_color_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mockups', to='mockups.color'),
        ),
    ]
