# Generated by Django 5.1.2 on 2024-10-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0018_mockup_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockup',
            name='relative_path',
            field=models.CharField(default='/', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
