# Generated by Django 5.1.2 on 2024-10-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0019_mockup_relative_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mockup',
            old_name='relative_path',
            new_name='mockup_relative_path',
        ),
    ]
