# Generated by Django 5.1.2 on 2024-10-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0020_rename_relative_path_mockup_mockup_relative_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mockup',
            name='mockup_box_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/box_mockups/', verbose_name='Mockup Box Image'),
        ),
        migrations.AlterField(
            model_name='mockup',
            name='mockup_image',
            field=models.ImageField(blank=True, null=True, upload_to='mockups/production_mockups/', verbose_name='Mockup Image'),
        ),
    ]
