# Generated by Django 5.1.2 on 2024-10-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0021_alter_mockup_mockup_box_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mockuplibrary',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
