# Generated by Django 5.1.2 on 2024-11-04 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mockups', '0022_mockuplibrary_description'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategory',
            new_name='MockupCategory',
        ),
        migrations.RenameField(
            model_name='mockup',
            old_name='product_category',
            new_name='mockup_category',
        ),
    ]
