# Generated by Django 5.1.2 on 2024-10-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
        ('mockups', '0014_mockuplibrary_mockups'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='mockup_libraries',
            field=models.ManyToManyField(blank=True, related_name='designs', to='mockups.mockuplibrary'),
        ),
        migrations.AddField(
            model_name='design',
            name='mockups',
            field=models.ManyToManyField(blank=True, related_name='designs', to='mockups.mockup'),
        ),
    ]
