# Generated by Django 5.1.2 on 2024-10-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_mockup_libraries_design_mockups'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_relative_path',
            field=models.CharField(default='/', editable=False, max_length=255),
            preserve_default=False,
        ),
    ]
