# Generated by Django 5.1.2 on 2024-10-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_design_relative_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='design_relative_path',
            field=models.CharField(max_length=255),
        ),
    ]
