# Generated by Django 5.1.2 on 2024-10-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_design_design_relative_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='file_name',
            field=models.CharField(default='noname', editable=False, max_length=255, verbose_name='Design File Name'),
            preserve_default=False,
        ),
    ]
