# Generated by Django 5.1.2 on 2024-10-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_design_file_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('In Progress', 'Inprogress'), ('Published', 'Published'), ('Retired', 'Retired'), ('Deleted', 'Deleted')], default='New', max_length=30, verbose_name='Status'),
        ),
    ]
