# Generated by Django 5.1.2 on 2024-11-04 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0007_alter_design_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='mockup_libraries',
        ),
        migrations.RemoveField(
            model_name='design',
            name='mockups',
        ),
    ]
