# Generated by Django 5.1.2 on 2024-11-04 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
